version: '3'
services:
  web:
    image: nginx
    container_name: diary-nginx
    ports:
      - '8080:80'
    links:
      - app
    volumes:
      - ./web/nginx.conf:/etc/nginx/nginx.conf
      - ./web/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - shared
      - private-diary
    environment:
      - VIRTUAL_HOST=diary.wastepipe.net
    restart: always

  app:
    image: tdiary/tdiary
    container_name: diary-app
    volumes:
      - ./app/.htaccess:/usr/src/app/.htaccess
      - ./app/.htpasswd:/usr/src/app/data/.htpasswd
      - ./app/tdiary.conf:/usr/src/app/tdiary.conf
      - ./app/data:/usr/src/data
      - ./app/theme:/usr/src/app/theme
      - ./app/plugin/bootstrap-navi.rb:/usr/src/app/misc/plugin/bootstrap-navi.rb
    networks:
      - private-diary
    restart: always

networks:
  shared:
    external: true
  private-diary:
    external: true
