version: '3'
services:
  web:
    image: nginx
    container_name: diary-nginx
    ports:
      - "${VIRTUAL_PORT}:80"
    links:
      - app
    volumes:
      - ./web/nginx.conf:/etc/nginx/nginx.conf
      - ./web/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - shared
      - private-diary
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - VIRTUAL_PORT=${VIRTUAL_PORT}
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    restart: always

  app:
    build:
      context: ./app
      args:
        APP_UID: ${APP_UID}
        APP_GID: ${APP_GID}
    container_name: diary-app
    volumes:
      - ./app/.htaccess:/usr/src/app/.htaccess
      - ./app/public:/usr/src/app/public
      - ./app/data:/usr/src/app/data
      - ./app/theme:/usr/src/app/theme
      - ./app/plugin/bootstrap-navi.rb:/usr/src/app/misc/plugin/bootstrap-navi.rb
    networks:
      - private-diary
    restart: always

networks:
  shared:
    external: true
  private-diary:
    external: false
