version: '3'
services:
  web:
    image: nginx
    container_name: www-nginx
    ports:
      - '8081:80'
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./html:/usr/share/nginx/html
    networks:
      - shared
      - private-www
    environment:
      - VIRTUAL_HOST=www.wastepipe.net,wastepipe.net
    restart: always

networks:
  shared:
    external: true
  private-www:
    external: true
