version: '3'

services:
  wordpress:
    image: wordpress:latest
    depends_on:
      - mysql
    env_file: .env
    ports:
      - $APP_PORT:80
    environment:
      - WORDPRESS_DB_HOST=mysql
      - WORDPRESS_DB_NAME=${APP_DATABASE_NAME}
      - WORDPRESS_DB_USER=${APP_DATABASE_USER}
      - WORDPRESS_DB_PASSWORD=${APP_DATABASE_PASSWORD}
      - VIRTUAL_HOST=blog.wastepipe.net
    volumes:
      - wordpress-html:/var/www/html
    networks:
      - shared
      - private-blog
    restart: always

  mysql:
    image: mysql:5.7
    env_file: .env
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=${APP_DATABASE_NAME}
      - MYSQL_USER=${APP_DATABASE_USER}
      - MYSQL_PASSWORD=${APP_DATABASE_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - private-blog
    restart: always

volumes:
  wordpress-html:
  mysql-data:

networks:
  shared:
    external: true
  private-blog:
    external: true
