version: '3'

services:
  app:
    build:
      context: ./app
      args:
        APP_UID: ${APP_UID}
        APP_GID: ${APP_GID}
    container_name: blog-app
    links:
      - mysql
    ports:
      - "$VIRTUAL_PORT:80"
    environment:
      - WORDPRESS_DB_HOST=mysql
      - WORDPRESS_DB_NAME=${APP_DATABASE_NAME}
      - WORDPRESS_DB_USER=${APP_DATABASE_USER}
      - WORDPRESS_DB_PASSWORD=${APP_DATABASE_PASSWORD}
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - VIRTUAL_PORT=${VIRTUAL_PORT}
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    volumes:
      - ./app/wp-content:/var/www/html/wp-content
    networks:
      - shared
      - private-blog
    restart: always

  mysql:
    image: mysql:5.7
    container_name: blog-db
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=${APP_DATABASE_NAME}
      - MYSQL_USER=${APP_DATABASE_USER}
      - MYSQL_PASSWORD=${APP_DATABASE_PASSWORD}
    volumes:
      - ./db/data:/var/lib/mysql
    networks:
      - private-blog
    restart: always

networks:
  shared:
    external: true
  private-blog:
    external: false
