version: '3'
services:
  nginx:
    image: jwilder/nginx-proxy
    container_name: proxy-nginx
    ports:
      - '80:80'
    volumes:
      - '/var/run/docker.sock:/tmp/docker.sock:ro'

networks:
  default:
    external:
      name: shared
